#============================================
# FORMATOS PDF
#============================================
rutas_pdf:

  rete_ica:
    ruta_nube: "/Innovación y tecnología/IntegrIA/Proyectos Automatización/11 Medios Magnéticos/insumos/reta_ica/CLIENTE/"
    ruta_carpeta: "medios_distritales/insumos/rete_ica/CLIENTE/"

  ica:
    ruta_nube: "/Innovación y tecnología/IntegrIA/Proyectos Automatización/11 Medios Magnéticos/insumos/ica/CLIENTE/"
    ruta_carpeta: "medios_distritales/insumos/ica/CLIENTE/"

  
