#============================================
# FORMATOS PDF
#============================================
rutas_pdf:

  rete_ica:
    ruta_nube: "/Innovación y tecnología/IntegrIA/Proyectos Automatización/11 Medios Distritales/insumos/rete_ica/CLIENTE/"
    ruta_carpeta: "insumos/rete_ica/CLIENTE/"
    BR: 0
    RP: 1
    DR: 2
    BH: 3
    VS: 4
    HA: 5
    VP: 6
    IM: 7
    TP: 8

  ica:
    ruta_nube: "/Innovación y tecnología/IntegrIA/Proyectos Automatización/11 Medios Distritales/insumos/ica/CLIENTE/"
    ruta_carpeta: "insumos/ica/CLIENTE/"
    BA: 1
    BC: 2
    BT: 3
    BB: 4
    IE: 5
    AF: 6
    BD: 7
    BE: 8
    IC: 9
    BF: 10
    BG: 11
    FU: 12
    BI: 13
    VS: 14
    DT: 15
    HA: 16
    VP: 17
    IM: 18
    TP: 19


  
